source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!

target ‘PatientApp’ do
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'SDWebImage', '~> 4.0'
end
