source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!

target ‘PatientApp’ do
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'FirebaseUI/Storage'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'FSCalendar'
end
