source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ’11.0’
use_frameworks!

target ‘DoctorApp’ do
    pod 'Firebase/Core'
    pod 'Firebase/Firestore'
    pod 'MBProgressHUD', '~> 1.0.0'
end
